name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Show workspace and install Python deps safely
        env:
          pythonLocation: /opt/hostedtoolcache/Python/${{ matrix.python-version }}/x64
        run: |
          echo "Working directory: $(pwd)"
          echo "Listing files:"
          ls -la
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            echo "Found requirements.txt, installing..."
            python -m pip install -r requirements.txt
          else
            echo "requirements.txt not found — skipping dependency install"
          fi

      - name: Run tests (if present)
        run: |
          if command -v pytest >/dev/null 2>&1 && ( [ -f pytest.ini ] || [ -d tests ] ); then
            pytest -q
          else
            echo "No pytest configuration or tests/ directory found — skipping tests"
          fi
